[workflow-manager] Add rbac settings
FRINXio/helm-charts pull request #382
Opened 2024-06-27 12:11 UTC by JumasJM

#### Checklist

- [ ] Title of the PR starts with chart name (e.g. `[krakend]`)
- [ ] Update the documentation if a new value has been added
- [ ] Update chart release notes *[annotation](https://artifacthub.io/docs/topics/annotations/helm/)*

2024-07-01 11:09 UTC, Jozefiel approved these changes

2024-07-01 11:10 UTC, Jozefiel requested changes
this should be also changed

2024-07-01 11:11 UTC, Jozefiel commented on charts/workflow-manager/Chart.yaml
>      - name: schellar
update image tags

2024-07-01 12:12 UTC, JumasJM commented on charts/workflow-manager/Chart.yaml
>      - name: schellar
updated

2024-07-08 13:27 UTC, Jozefiel approved these changes

2024-07-08 13:27 UTC, merged